Hr_system/Controllers/HeadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hr_system.Models;
using Microsoft.AspNetCore.Authorization;

namespace Hr_system.Controllers
{

    [Authorize(Roles = "admin")]
    public class HeadsController : Controller
    {
        private readonly HrContext _context;

        public HeadsController(HrContext context)
        {
            _context = context;
        }

        // GET: Admin/Heads
        public async Task<IActionResult> Index()
        {
            return View(await _context.Heads.ToListAsync());
        }

        // GET: Admin/Heads/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var head = await _context.Heads
                .FirstOrDefaultAsync(m => m.Id == id);
            if (head == null)
            {
                return NotFound();
            }

            return View(head);
        }

        // GET: Admin/Heads/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Name");
            return View();
        }

        // POST: Admin/Heads/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Boss")] Head head)
        {
            if (ModelState.IsValid)
            {
                _context.Add(head);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(head);
        }

        // GET: Admin/Heads/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var head = await _context.Heads.FindAsync(id);
            if (head == null)
            {
                return NotFound();
            }
          
            return View(head);
        }

        // POST: Admin/Heads/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Boss")] Head head)
        {
            if (id != head.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(head);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HeadExists(head.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
         
            return View(head);
        }

        // GET: Admin/Heads/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var head = await _context.Heads
                .FirstOrDefaultAsync(m => m.Id == id);
            if (head == null)
            {
                return NotFound();
            }

            return View(head);
        }

        // POST: Admin/Heads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var head = await _context.Heads.FindAsync(id);
            _context.Heads.Remove(head);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HeadExists(int id)
        {
            return _context.Heads.Any(e => e.Id == id);
        }
    }
}

Hr_system/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Hr_system.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Hr_system.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace Hr_system.Controllers
{
 
    [Authorize(Roles = "admin")]
    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;
        private UserManager<User> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private HrContext _context;
        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager, IWebHostEnvironment webHostEnvironment
            , HrContext context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
            _context = context;
        }


        public ViewResult Index() => View(_roleManager.Roles);

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create([Required] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            return View(name);
        }

      
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            else
                ModelState.AddModelError("", "No role found");
            return View("Index", _roleManager.Roles);
        }

        public async Task<IActionResult> Update(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            List<User> members = new List<User>();
            List<User> nonMembers = new List<User>();
            foreach (User user in _userManager.Users)
            {
                var list = await _userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEdit
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<IActionResult> Update(RoleModification model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.AddIds ?? new string[] { })
                {
                    User user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
                foreach (string userId in model.DeleteIds ?? new string[] { })
                {
                    User user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
            }

            if (ModelState.IsValid)
                return RedirectToAction(nameof(Index));
            else
                return await Update(model.RoleId);
        }



        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
    }
}

Hr_system/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Hr_system.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hr_system.Controllers
{
    
    [Authorize]
    public class UserController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private HrContext _context;
        private UserManager<User> _userManager;
        public UserController(IWebHostEnvironment webHostEnvironment,HrContext context, UserManager<User> usermanager)
        {
            _webHostEnvironment = webHostEnvironment;
            _context = context;
            _userManager = usermanager;
        }
        public async Task<IActionResult> Index(string searchString, string currentFilter, int? pageNumber)
        {
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            var users = from s in _context.Users
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(s => s.UserName.Contains(searchString)
                                       || s.Email.Contains(searchString) ||
                                      s.Pretending.NameOfPlace.Contains(searchString) ||
                                      s.Pretending.Head.Name.Contains(searchString));
            }
            ViewData["SpecialityId"] = (_context.Specialities, "Id", "Name");
            ViewData["PretendingId"] = (_context.Pretedings, "Id", "NameOfPlace");

            int pageSize = 5;
            return View(await PaginatedList<User>.CreateAsync(users.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }
        [Authorize(Roles = "admin")]
        public IActionResult CreateUser()
        {
            ViewData["SpecialityId"] = new SelectList(_context.Specialities, "Id", "Name");
            ViewData["PretendingId"] = new SelectList(_context.Pretedings, "Id", "NameOfPlace");
           
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateUser([Bind("Email,UserName,Password,SpecialityId,PretendingId,MeetTime,Link,Rating,Comment," +
            "NameOfExamenator,Resume")]User user)
        {
            if (ModelState.IsValid)
            {
                if (user.Resume != null)
                {
                    string folderPath = Path.Combine(_webHostEnvironment.WebRootPath, "SomeFiles", "Resumes");
                    string fileName = $"{Guid.NewGuid().ToString()}_{user.Resume.FileName}";
                    string filePath = Path.Combine(folderPath, fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        user.Resume.CopyTo(stream);
                    }


                }
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SpecialityId"] = new SelectList(_context.Specialities, "Id", "Name", user.SpecialityId);
            ViewData["PretendingId"] = new SelectList(_context.Pretedings, "Id", "NameOfPlace",user.PretendingId);
            return View(user);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["PretendingId"] = new SelectList(_context.Pretedings, "Id", "Id", user.PretendingId);
            ViewData["SpecialityId"] = new SelectList(_context.Specialities, "Id", "Id", user.SpecialityId);
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SpecialityId,PretendingId,MeetTime,Link,Rating,Comment,Resume")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (user.Resume != null)
                    {
                        string folderPath = Path.Combine(_webHostEnvironment.WebRootPath, "SomeFiles", "Resumes");
                        string fileName = $"{Guid.NewGuid().ToString()}_{user.Resume.FileName}";
                        string filePath = Path.Combine(folderPath, fileName);

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            user.Resume.CopyTo(stream);
                        }

 
                    }
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PretendingId"] = new SelectList(_context.Pretedings, "Id", "Id", user.PretendingId);
            ViewData["SpecialityId"] = new SelectList(_context.Specialities, "Id", "Id", user.SpecialityId);
            return View(user);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Admin/Phones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Search(string search)
        {
            List<User> users = await _userManager.Users.Where(p => p.Email.Contains(search) || p.UserName.Contains(search)).ToListAsync();
            return View(users);
        }

        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Hr_system/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HR System </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HR Система</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Домой</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">
                                Пользователи
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Specialities" asp-action="Index">
                                Специальности
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Heads" asp-action="Index">
                                Отделы
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pretendings" asp-action="Index">
                                Должности
                            </a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">
                            Роли
                        </a>
                    </li>
                        }



                                    @if (User.Identity.IsAuthenticated)
                                    {
                    <li class="nav-item">
                        <form method="post" asp-controller="Account" asp-action="LogOff" class="nav-link text-dark">
                            <input type="submit" value="@User.Identity.Name Выход" class="form-control" />
                        </form>

                    </li> }
                                    else
                                    {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Вход</a>
                    </li>
}



                                                </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MobilePhones - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>